# Generated by Django 5.1 on 2026-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_cancel', 'Order Cancelled'), ('item_cancel', 'Item Cancelled'), ('return_approved', 'Return Approved'), ('wallet_topup', 'Wallet Top-up'), ('order_payment', 'Order Payment')], max_length=20),
        ),
    ]
