# Generated by Django 5.1 on 2026-01-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_inventory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_category_products', to='product.category'),
        ),
    ]
