# Generated by Django 5.1 on 2026-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadmin', '0002_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True),
        ),
    ]
