# Generated by Django 5.1 on 2026-08-03 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='First name can contain only letters, spaces, hyphens, or apostrophes.', regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$")]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Last name can contain only letters, spaces, hyphens, or apostrophes.', regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$")]),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/customer/profile_image'),
        ),
    ]
