# Generated by Django 5.1 on 2026-08-03 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
